[package]
name = "armfault"
version = "0.1.0"
authors = ["Michael Zimmermann <michael.zimmermann@grandcentrix.net>"]
edition = "2018"

[dependencies]
arc-swap = "0.4.2"

[profile.release]
lto = true
opt-level = 2
